module.exports = {
    nameEngToKr(nameEng) {
        return engToKrChampion[nameEng];
    },

    nameKrToEng(nameKr) {
        return krToEngChampion[nameKr];
    },

    itemNumberToName(number) {
        return numberToNameItem[number];
    },

    itemNameToNumber(name) {
        return nameToNumberItem[name];
    },
    
    isValidChampionName(name) {
        return krToEngChampion.hasOwnProperty(name);
    },
}

const engToKrChampion = {
    "Jinx" : "징크스",
    "Sett" : "세트",
    "Galio" : "갈리오",
    "Morgana" : "모르가나",
    "Brand" : "브랜드",
    "Vel'Koz" : "벨코즈",
    "Swain" : "스웨인",
    "Cho'Gath" : "초가스",
    "Lux" : "럭스",
    "Kog'Maw" : "코그모",
    "Xayah" : "자야",
    "Fiddlesticks" : "피들스틱",
    "Vayne" : "베인",
    "Sona" : "소나",
    "Zyra" : "자이라",
    "Ziggs" : "직스",
    "Kayle" : "케일",
    "Thresh" : "쓰레쉬",
    "Sion" : "사이온",
    "Nami" : "나미",
    "Mel" : "멜",
    "Yuumi" : "유미",
    "Xerath" : "제라스",
    "Ashe" : "애쉬",
    "Annie" : "애니",
    "Malzahar" : "말자하",
    "Maokai" : "마오카이",
    "Twitch" : "트위치",
    "Nautilus" : "노틸러스",
    "Caitlyn" : "케이틀린",
    "Heimerdinger" : "하이머딩거",
    "Hwei" : "흐웨이",
    "Milio" : "밀리오",
    "Gnar" : "나르",
    "lllaoi" : "일라오이",
    "Nasus" : "나서스",
    "Darius" : "다리우스",
    "Shen" : "쉔",
    "Dr. Mundo" : "문도박사",
    "Kennen" : "케넨",
    "Janna" : "잔나",
    "Sivir" : "시비르",
    "Braum" : "브라움",
    "Leona" : "레오나",
    "Wukong" : "오공",
    "Aurelion Sol" : "아우렐리온솔",
    "Amumu" : "아무무",
    "Rell" : "렐",
    "Teemo" : "티모",
    "Ornn" : "오른",
    "Alistar" : "알리스타",
    "Viktor" : "빅토르",
    "Twisted Fate" : "트위스티드페이트",
    "Aphelios" : "아펠리오스",
    "Kalista" : "칼리스타",
    "Vex" : "벡스",
    "Lissandra" : "리산드라",
    "Yorick" : "요릭",
    "Tristana" : "트리스타나",
    "Taric" : "타릭",
    "Kindred" : "킨드레드",
    "Trundle" : "트런들",
    "Xin Zhao" : "신짜오",
    "Poppy" : "뽀삐",
    "Varus" : "바루스",
    "Anivia" : "애니비아",
    "Ryze" : "라이즈",
    "Yasuo" : "야스오",
    "Urgot" : "우르곳",
    "Mordekaiser" : "모데카이저",
    "Volibear" : "볼리베어",
    "Karthus" : "카서스",
    "Diana" : "다이애나",
    "Jax" : "잭스",
    "Vi" : "바이",
    "Renata Glasc" : "레나타글라스크",
    "Gragas" : "그라가스",
    "Tahm Kench" : "탐켄치",
    "Neeko" : "니코",
    "Rumble" : "럼블",
    "Taliyah" : "탈리야",
    "Senna" : "세나",
    "Olaf" : "올라프",
    "Sejuani" : "세주아니",
    "Singed" : "신지드",
    "Gangplank" : "갱플랭크",
    "Rek'Sai" : "렉사이",
    "Gwen" : "그웬",
    "Lulu" : "룰루",
    "Azir" : "아지르",
    "Lillia" : "릴리아",
    "Ivern" : "아이번",
    "Tryndamere" : "트린다미어",
    "Kled" : "클레드",
    "Riven" : "리븐",
    "Udyr" : "우디르",
    "Seraphine" : "세라핀",
    "Ezreal" : "이즈리얼",
    "Cassiopeia" : "카시오페아",
    "Briar" : "브라이어",
    "Viego" : "비에고",
    "Nilah" : "닐라",
    "Warwick" : "워윅",
    "Skarner" : "스카너",
    "Renekton" : "레넥톤",
    "Jhin" : "진",
    "Orianna" : "오리아나",
    "Pantheon" : "판테온",
    "Aatrox" : "아트록스",
    "Blitzcrank" : "블리츠크랭크",
    "Kayn" : "케인",
    "Elise" : "엘리스",
    "Samira" : "사미라",
    "Zoe" : "조이",
    "Hecarim" : "헤카림",
    "Rakan" : "라칸",
    "Camille" : "카밀",
    "Yone" : "요네",
    "Smolder" : "스몰더",
    "Rammus" : "람머스",
    "Naafiri" : "나피리",
    "Karma" : "카르마",
    "Quinn" : "퀸",
    "Master Yi" : "마스터이",
    "Jarvan IV" : "자르반4세",
    "Zac" : "자크",
    "Corki" : "코르키",
    "Nocturne" : "녹턴",
    "Ambessa" : "암베사",
    "Akshan" : "아크샨",
    "Bel'Veth" : "벨베스",
    "Fiora" : "피오라",
    "Shyvana" : "쉬바나",
    "Evelynn" : "이블린",
    "Kassadin" : "카사딘",
    "Malphite" : "말파이트",
    "Veigar" : "베이가",
    "Ahri" : "아리",
    "Irelia" : "이렐리아",
    "Syndra" : "신드라",
    "Miss Fortune" : "미스포츈",
    "Garen" : "가렌",
    "Lucian" : "루시안",
    "Vladimir" : "블라디미르",
    "Zeri" : "제리",
    "Shaco" : "샤코",
    "Ekko" : "에코",
    "K'Sante" : "크산테",
    "Rengar" : "렝가",
    "Sylas" : "사일러스",
    "Zilean" : "질리언",
    "Talon" : "탈론",
    "Qiyana" : "키아나",
    "Aurora" : "오로라",
    "Jayce" : "제이스",
    "Graves" : "그레이브즈",
    "Nidalee" : "니달리",
    "Fizz" : "피즈",
    "Nunu & Willump" : "누누와윌럼프",
    "Bard" : "바드",
    "Lee Sin" : "리신",
    "Soraka" : "소라카",
    "Draven" : "드레이븐",
    "Kai'Sa" : "카이사",
    "Kha'Zix" : "카직스",
    "Akali" : "아칼리",
    "Katarina" : "카타리나",
    "Zed" : "제드",
    "LeBlanc" : "르블랑",
    "Pyke" : "파이크"
};

//OP.GG 링크에서 사용하는 챔피언 영문 명으로 변환
const krToEngChampion = {
    '징크스': 'Jinx',
    '세트': 'Sett',
    '갈리오': 'Galio',
    '모르가나': 'Morgana',
    '브랜드': 'Brand',
    '벨코즈': "VelKoz",
    '스웨인': 'Swain',
    '초가스': "ChoGath",
    '럭스': 'Lux',
    '코그모': "KogMaw",
    '자야': 'Xayah',
    '피들스틱': 'Fiddlesticks',
    '피들': 'Fiddlesticks',
    '베인': 'Vayne',
    '소나': 'Sona',
    '자이라': 'Zyra',
    '직스': 'Ziggs',
    '케일': 'Kayle',
    '쓰레쉬': 'Thresh',
    '사이온': 'Sion',
    '나미': 'Nami',
    '멜': 'Mel',
    '유미': 'Yuumi',
    '제라스': 'Xerath',
    '애쉬': 'Ashe',
    '애니': 'Annie',
    '말자하': 'Malzahar',
    '마오카이': 'Maokai',
    '트위치': 'Twitch',
    '노틸러스': 'Nautilus',
    '노틸': 'Nautilus',
    '케이틀린': 'Caitlyn',
    '케틀': 'Caitlyn',
    '하이머딩거': 'Heimerdinger',
    '하딩': 'Heimerdinger',
    '하이머': 'Heimerdinger',
    '흐웨이': 'Hwei',
    '밀리오': 'Milio',
    '나르': 'Gnar',
    '일라오이': 'lllaoi',
    '일라': 'lllaoi',
    '나서스': 'Nasus',
    '다리우스': 'Darius',
    '다리': 'Darius',
    '쉔': 'Shen',
    '문도박사': 'DrMundo',
    '문도': 'DrMundo',
    '케넨': 'Kennen',
    '잔나': 'Janna',
    '시비르': 'Sivir',
    '브라움': 'Braum',
    '레오나': 'Leona',
    '오공': 'Monkeyking',
    '아우렐리온솔': 'AurelionSol',
    '아우솔': 'AurelionSol',
    '아무무': 'Amumu',
    '렐': 'Rell',
    '티모': 'Teemo',
    '오른': 'Ornn',
    '알리스타': 'Alistar',
    '알리': 'Alistar',
    '빅토르': 'Viktor',
    '트위스티드페이트': 'TwistedFate',
    '트페': 'TwistedFate',
    '아펠리오스': 'Aphelios',
    '아펠': 'Aphelios',
    '칼리스타': 'Kalista',
    '칼리': 'Kalista',
    '벡스': 'Vex',
    '리산드라': 'Lissandra',
    '리산': 'Lissandra',
    '요릭': 'Yorick',
    '트리스타나': 'Tristana',
    '트리': 'Tristana',
    '트타': 'Tristana',
    '타릭': 'Taric',
    '킨드레드': 'Kindred',
    '킨드': 'Kindred',
    '트런들': 'Trundle',
    '신짜오': 'XinZhao',
    '짜오': 'XinZhao',
    '뽀삐': 'Poppy',
    '바루스': 'Varus',
    '애니비아': 'Anivia',
    '라이즈': 'Ryze',
    '야스오': 'Yasuo',
    '우르곳': 'Urgot',
    '모데카이저': 'Mordekaiser',
    '모데': 'Modekaiser',
    '볼리베어': 'Volibear',
    '볼베': 'Volibear',
    '카서스': 'Karthus',
    '다이애나': 'Diana',
    '잭스': 'Jax',
    '바이': 'Vi',
    '레나타글라스크': 'RenataGlasc',
    '레나타': 'RenataGlasc',
    '그라가스': 'Gragas',
    '그라': 'Gragas',
    '글가': 'Gragas',
    '탐켄치': 'TahmKench',
    '켄치': 'TahmKench',
    '니코': 'Neeko',
    '럼블': 'Rumble',
    '탈리야': 'Taliyah',
    '세나': 'Senna',
    '올라프': 'Olaf',
    '세주아니': 'Sejuani',
    '세주': 'Sejuani',
    '신지드': 'Singed',
    '갱플랭크': 'Gangplank',
    '갱플': 'Gangplank',
    '렉사이': "RekSai",
    '그웬': 'Gwen',
    '룰루': 'Lulu',
    '아지르': 'Azir',
    '릴리아': 'Lillia',
    '아이번': 'Ivern',
    '트린다미어': 'Tryndamere',
    '트린': 'Tryndamere',
    '클레드': 'Kled',
    '리븐': 'Riven',
    '우디르': 'Udyr',
    '세라핀': 'Seraphine',
    '이즈리얼': 'Ezreal',
    '이즈': 'Ezreal',
    '카시오페아': 'Cassiopeia',
    '카시': 'Cassiopeia',
    '브라이어': 'Briar',
    '브라': 'Briar',
    '비에고': 'Viego',
    '닐라': 'Nilah',
    '워윅': 'Warwick',
    '스카너': 'Skarner',
    '레넥톤': 'Renekton',
    '레넥': 'Renekton',
    '진': 'Jhin',
    '오리아나': 'Orianna',
    '오리': 'Orianna',
    '판테온': 'Pantheon',
    '판테': 'Pantheon',
    '아트록스': 'Aatrox',
    '아트': 'Aatrox',
    '블리츠크랭크': 'Blitzcrank',
    '블츠': 'Blitzcrank',
    '블크': 'Blitzcrank',
    '케인': 'Kayn',
    '엘리스': 'Elise',
    '사미라': 'Samira',
    '조이': 'Zoe',
    '헤카림': 'Hecarim',
    '라칸': 'Rakan',
    '카밀': 'Camille',
    '요네': 'Yone',
    '스몰더': 'Smolder',
    '람머스': 'Rammus',
    '나피리': 'Naafiri',
    '카르마': 'Karma',
    '퀸': 'Quinn',
    '마스터이': 'MasterYi',
    '마이': 'MasterYi',
    '자르반4세': 'JarvanIV',
    '자르반': 'JarvanIV',
    '자크': 'Zac',
    '코르키': 'Corki',
    '녹턴': 'Nocturne',
    '암베사': 'Ambessa',
    '아크샨': 'Akshan',
    '벨베스': "BelVeth",
    '피오라': 'Fiora',
    '쉬바나': 'Shyvana',
    '이블린': 'Evelynn',
    '카사딘': 'Kassadin',
    '말파이트': 'Malphite',
    '말파': 'Malphite',
    '베이가': 'Veigar',
    '아리': 'Ahri',
    '이렐리아': 'Irelia',
    '이렐': 'Irelia',
    '신드라': 'Syndra',
    '미스포츈': 'MissFortune',
    '미포': 'MissFortune',
    '가렌': 'Garen',
    '루시안': 'Lucian',
    '블라디미르': 'Vladimir',
    '블라디': 'Vladimir',
    '제리': 'Zeri',
    '샤코': 'Shaco',
    '에코': 'Ekko',
    '크산테': "KSante",
    '렝가': 'Rengar',
    '사일러스': 'Sylas',
    '사일': 'Sylas',
    '질리언': 'Zilean',
    '탈론': 'Talon',
    '키아나': 'Qiyana',
    '오로라': 'Aurora',
    '제이스': 'Jayce',
    '그레이브즈': 'Graves',
    '그브': 'Graves',
    '니달리': 'Nidalee',
    '피즈': 'Fizz',
    '누누와윌럼프': 'Nunu',
    '누누': 'Nunu',
    '바드': 'Bard',
    '리신': 'LeeSin',
    '소라카': 'Soraka',
    '드레이븐': 'Draven',
    '드븐': 'Draven',
    '카이사': "Kaisa",
    '카직스': "Khazix",
    '아칼리': 'Akali',
    '카타리나': 'Katarina',
    '카타': 'Katarina',
    '제드': 'Zed',
    '르블랑': 'LeBlanc',
    '파이크': 'Pyke'
};

const numberToNameItem = {
    '1001': 'Boots',
    '1004': 'Faerie Charm',
    '1006': 'Rejuvenation Bead',
    '1011': "Giant's Belt",
    '1018': 'Cloak of Agility',
    '1026': 'Blasting Wand',
    '1027': 'Sapphire Crystal',
    '1028': 'Ruby Crystal',
    '1029': 'Cloth Armor',
    '1036': 'Long Sword',
    '1037': 'Pickaxe',
    '1038': 'B. F. Sword',
    '1042': 'Dagger',
    '1043': 'Recurve Bow',
    '1052': 'Amplifying Tome',
    '1053': 'Vampiric Scepter',
    '1054': "Doran's Shield",
    '1055': "Doran's Blade",
    '1056': "Doran's Ring",
    '1082': 'Dark Seal',
    '1083': 'Cull',
    '1101': 'Scorchclaw Pup',
    '1102': 'Gustwalker Hatchling',
    '1103': 'Mosstomper Seedling',
    '2003': 'Health Potion',
    '2020': 'The Brutalizer',
    '2021': 'Tunneler',
    '2022': 'Glowing Mote',
    '2031': 'Refillable Potion',
    '2051': "Guardian's Horn",
    '2065': "Shurelya's Battlesong",
    '2420': "Seeker's Armguard",
    '2501': "Overlord's Bloodmail",
    '2502': 'Unending Despair',
    '2503': 'Blackfire Torch',
    '2504': 'Kaenic Rookern',
    '2508': 'Fated Ashes',
    '3002': 'Trailblazer',
    '3003': "Archangel's Staff",
    '3004': 'Manamune',
    '3006': "Berserker's Greaves",
    '3009': 'Boots of Swiftness',
    '3020': "Sorcerer's Shoes",
    '3026': 'Guardian Angel',
    '3031': 'Infinity Edge',
    '3032': 'Yun Tal Wildarrows',
    '3033': 'Mortal Reminder',
    '3036': "Lord Dominik's Regards",
    '3040': "Seraph's Embrace",
    '3044': 'Phage',
    '3046': 'Phantom Dancer',
    '3047': 'Plated Steelcaps',
    '3050': "Zeke's Convergence",
    '3051': 'Hearthbound Axe',
    '3053': "Sterak's Gage",
    '3057': 'Sheen',
    '3065': 'Spirit Visage',
    '3067': 'Kindlegem',
    '3068': 'Sunfire Aegis',
    '3070': 'Tear of the Goddess',
    '3071': 'Black Cleaver',
    '3072': 'Bloodthirster',
    '3073': 'Experimental Hexplate',
    '3074': 'Ravenous Hydra',
    '3075': 'Thornmail',
    '3076': 'Bramble Vest',
    '3077': 'Tiamat',
    '3078': 'Trinity Force',
    '3083': "Warmog's Armor",
    '3084': 'Heartsteel',
    '3085': "Runaan's Hurricane",
    '3087': 'Statikk Shiv',
    '3089': "Rabadon's Deathcap",
    '3091': "Wit's End",
    '3094': 'Rapid Firecannon',
    '3100': 'Lich Bane',
    '3102': "Banshee's Veil",
    '3105': 'Aegis of the Legion',
    '3107': 'Redemption',
    '3108': 'Fiendish Codex',
    '3109': "Knight's Vow",
    '3110': 'Frozen Heart',
    '3111': "Mercury's Treads",
    '3112': "Guardian's Orb",
    '3114': 'Forbidden Idol',
    '3115': "Nashor's Tooth",
    '3116': "Rylai's Crystal Scepter",
    '3118': 'Malignance',
    '3119': "Winter's Approach",
    '3121': 'Fimbulwinter',
    '3123': "Executioner's Calling",
    '3124': "Guinsoo's Rageblade",
    '3134': 'Serrated Dirk',
    '3135': 'Void Staff',
    '3137': 'Cryptbloom',
    '3139': 'Mercurial Scimitar',
    '3142': "Youmuu's Ghostblade",
    '3143': "Randuin's Omen",
    '3144': "Scout's Slingshot",
    '3145': 'Hextech Alternator',
    '3147': 'Haunting Guise',
    '3152': 'Hextech Rocketbelt',
    '3153': 'Blade of The Ruined King',
    '3156': 'Maw of Malmortius',
    '3157': "Zhonya's Hourglass",
    '3158': 'Ionian Boots of Lucidity',
    '3161': 'Spear of Shojin',
    '3165': 'Morellonomicon',
    '3177': "Guardian's Blade",
    '3179': 'Umbral Glaive',
    '3181': 'Hullbreaker',
    '3184': "Guardian's Hammer",
    '3190': 'Locket of the Iron Solari',
    '3211': "Spectre's Cowl",
    '3222': "Mikael's Blessing",
    '3302': 'Terminus',
    '3504': 'Ardent Censer',
    '3508': 'Essence Reaver',
    '3742': "Dead Man's Plate",
    '3748': 'Titanic Hydra',
    '3801': 'Crystalline Bracer',
    '3802': 'Lost Chapter',
    '3803': 'Catalyst of Aeons',
    '3814': 'Edge of Night',
    '3865': 'World Atlas',
    '3869': 'Celestial Opposition',
    '3870': 'Dream Maker',
    '3871': "Zaz'Zak's Realmspike",
    '3876': 'Solstice Sleigh',
    '3877': 'Bloodsong',
    '3916': 'Oblivion Orb',
    '4005': 'Imperial Mandate',
    '4401': 'Force of Nature',
    '4628': 'Horizon Focus',
    '4629': 'Cosmic Drive',
    '4633': 'Riftmaker',
    '4642': 'Bandleglass Mirror',
    '4645': 'Shadowflame',
    '4646': 'Stormsurge',
    '6333': "Death's Dance",
    '6609': 'Chempunk Chainsword',
    '6610': 'Sundered Sky',
    '6616': 'Staff of Flowing Water',
    '6617': 'Moonstone Renewer',
    '6620': 'Echoes of Helia',
    '6621': 'Dawncore',
    '6631': 'Stridebreaker',
    '6653': "Liandry's Torment",
    '6655': "Luden's Companion",
    '6657': 'Rod of Ages',
    '6660': "Bami's Cinder",
    '6662': 'Iceborn Gauntlet',
    '6664': 'Hollow Radiance',
    '6665': "Jak'Sho, The Protean",
    '6672': 'Kraken Slayer',
    '6673': 'Immortal Shieldbow',
    '6675': 'Navori Flickerblade',
    '6676': 'The Collector',
    '6690': 'Rectrix',
    '6692': 'Eclipse',
    '6694': "Serylda's Grudge",
    '6695': "Serpent's Fang",
    '6696': 'Axiom Arc',
    '6697': 'Hubris',
    '6698': 'Profane Hydra',
    '6699': 'Voltaic Cyclosword',
    '6701': 'Opportunity',
    '8010': "Bloodletter's Curse",
    '8020': 'Abyssal Mask'
}

const nameToNumberItem = {
    'Abyssal Mask': '8020',
    'Aegis of the Legion': '3105',
    'Amplifying Tome': '1052',
    "Archangel's Staff": '3003',
    'Ardent Censer': '3504',
    'Axiom Arc': '6696',
    'B. F. Sword': '1038',
    "Bami's Cinder": '6660',
    'Bandleglass Mirror': '4642',
    "Banshee's Veil": '3102',
    "Berserker's Greaves": '3006',
    'Black Cleaver': '3071',
    'Blackfire Torch': '2503',
    'Blade of The Ruined King': '3153',
    'Blasting Wand': '1026',
    "Bloodletter's Curse": '8010',
    'Bloodsong': '3877',
    'Bloodthirster': '3072',
    'Boots': '1001',
    'Boots of Swiftness': '3009',
    'Bramble Vest': '3076',
    'Catalyst of Aeons': '3803',
    'Celestial Opposition': '3869',
    'Chempunk Chainsword': '6609',
    'Cloak of Agility': '1018',
    'Cloth Armor': '1029',
    'Cosmic Drive': '4629',
    'Cryptbloom': '3137',
    'Crystalline Bracer': '3801',
    'Cull': '1083',
    'Dagger': '1042',
    'Dark Seal': '1082',
    'Dawncore': '6621',
    "Dead Man's Plate": '3742',
    "Death's Dance": '6333',
    "Doran's Blade": '1055',
    "Doran's Ring": '1056',
    "Doran's Shield": '1054',
    'Dream Maker': '3870',
    'Echoes of Helia': '6620',
    'Eclipse': '6692',
    'Edge of Night': '3814',
    'Essence Reaver': '3508',
    "Executioner's Calling": '3123',
    'Experimental Hexplate': '3073',
    'Faerie Charm': '1004',
    'Fated Ashes': '2508',
    'Fiendish Codex': '3108',
    'Fimbulwinter': '3121',
    'Forbidden Idol': '3114',
    'Force of Nature': '4401',
    'Frozen Heart': '3110',
    "Giant's Belt": '1011',
    'Glowing Mote': '2022',
    'Guardian Angel': '3026',
    "Guardian's Blade": '3177',
    "Guardian's Hammer": '3184',
    "Guardian's Horn": '2051',
    "Guardian's Orb": '3112',
    "Guinsoo's Rageblade": '3124',
    'Gustwalker Hatchling': '1102',
    'Haunting Guise': '3147',
    'Health Potion': '2003',
    'Hearthbound Axe': '3051',
    'Heartsteel': '3084',
    'Hextech Alternator': '3145',
    'Hextech Rocketbelt': '3152',
    'Hollow Radiance': '6664',
    'Horizon Focus': '4628',
    'Hubris': '6697',
    'Hullbreaker': '3181',
    'Iceborn Gauntlet': '6662',
    'Immortal Shieldbow': '6673',
    'Imperial Mandate': '4005',
    'Infinity Edge': '3031',
    'Ionian Boots of Lucidity': '3158',
    "Jak'Sho, The Protean": '6665',
    'Kaenic Rookern': '2504',
    'Kindlegem': '3067',
    "Knight's Vow": '3109',
    'Kraken Slayer': '6672',
    "Liandry's Torment": '6653',
    'Lich Bane': '3100',
    'Locket of the Iron Solari': '3190',
    'Long Sword': '1036',
    "Lord Dominik's Regards": '3036',
    'Lost Chapter': '3802',
    "Luden's Companion": '6655',
    'Malignance': '3118',
    'Manamune': '3004',
    'Maw of Malmortius': '3156',
    'Mercurial Scimitar': '3139',
    "Mercury's Treads": '3111',
    "Mikael's Blessing": '3222',
    'Moonstone Renewer': '6617',
    'Morellonomicon': '3165',
    'Mortal Reminder': '3033',
    'Mosstomper Seedling': '1103',
    'Muramana': '3042',
    "Nashor's Tooth": '3115',
    'Navori Flickerblade': '6675',
    'Oblivion Orb': '3916',
    'Opportunity': '6701',
    "Overlord's Bloodmail": '2501',
    'Phage': '3044',
    'Phantom Dancer': '3046',
    'Pickaxe': '1037',
    'Plated Steelcaps': '3047',
    'Profane Hydra': '6698',
    "Rabadon's Deathcap": '3089',
    "Randuin's Omen": '3143',
    'Rapid Firecannon': '3094',
    'Ravenous Hydra': '3074',
    'Rectrix': '6690',
    'Recurve Bow': '1043',
    'Redemption': '3107',
    'Refillable Potion': '2031',
    'Rejuvenation Bead': '1006',
    'Riftmaker': '4633',
    'Rod of Ages': '6657',
    'Ruby Crystal': '1028',
    "Runaan's Hurricane": '3085',
    "Rylai's Crystal Scepter": '3116',
    'Sapphire Crystal': '1027',
    'Scorchclaw Pup': '1101',
    "Scout's Slingshot": '3144',
    "Seeker's Armguard": '2420',
    "Seraph's Embrace": '3040',
    "Serpent's Fang": '6695',
    'Serrated Dirk': '3134',
    "Serylda's Grudge": '6694',
    'Shadowflame': '4645',
    'Sheen': '3057',
    "Shurelya's Battlesong": '2065',
    'Solstice Sleigh': '3876',
    "Sorcerer's Shoes": '3020',
    'Spear of Shojin': '3161',
    "Spectre's Cowl": '3211',
    'Spirit Visage': '3065',
    'Staff of Flowing Water': '6616',
    'Statikk Shiv': '3087',
    "Sterak's Gage": '3053',
    'Stormsurge': '4646',
    'Stridebreaker': '6631',
    'Sundered Sky': '6610',
    'Sunfire Aegis': '3068',
    'Tear of the Goddess': '3070',
    'Terminus': '3302',
    'The Brutalizer': '2020',
    'The Collector': '6676',
    'Thornmail': '3075',
    'Tiamat': '3077',
    'Titanic Hydra': '3748',
    'Trailblazer': '3002',
    'Trinity Force': '3078',
    'Tunneler': '2021',
    'Umbral Glaive': '3179',
    'Unending Despair': '2502',
    'Vampiric Scepter': '1053',
    'Void Staff': '3135',
    'Voltaic Cyclosword': '6699',
    "Warmog's Armor": '3083',
    "Winter's Approach": '3119',
    "Wit's End": '3091',
    'World Atlas': '3865',
    "Youmuu's Ghostblade": '3142',
    'Yun Tal Wildarrows': '3032',
    "Zaz'Zak's Realmspike": '3871',
    "Zeke's Convergence": '3050',
    "Zhonya's Hourglass": '3157'
}

